# Generated by Django 2.0.4 on 2018-04-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_auto_20180430_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api_v1.BankAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
